#!/bin/bash
#SBATCH -p medium
#SBATCH -N 1
#SBATCH -n 12
#SBATCH --time=12:00:00
#SBATCH --error=example.err
#SBATCH --output=example.out

module purge
module load sratoolkit/2.5.2
module load bowtie2/2.2.6
module load rsem/1.2.31

cd ~/epidb.processing/chicken/tissue/

fastq-dump --split-files ~/epidb.processing/chicken/tissue/example.sra

data_b="example_2.fastq"
if [ -e ${data_b} ]
    then rsem-calculate-expression -p 12 --paired-end --bowtie2 example_1.fastq example_2.fastq ~/index/gallus_gallus/RSEM/current_build example
else
    rsem-calculate-expression -p 12 --bowtie2 example_1.fastq ~/index/gallus_gallus/RSEM/current_build example
fi

