#!/bin/bash
#SBATCH -p medium
#SBATCH -N 1
#SBATCH -n 12
#SBATCH --time=12:00:00
#SBATCH --error=example.err
#SBATCH --output=example.out

module purge
module load samtools/1.3
module load python/2.7.12

cd ~/epidb.processing/chicken/tissue/

samtools view -h example.fixed.bam > example.fixed.sam

htseq-count -m intersection-nonempty -s no -i gene_id example.fixed.sam ~/index/gallus_gallus/RSEM/Gallus_gallus.Galgal4.85.gtf > example.htseq.txt

rm example.fixed.sam
